#!/usr/bin/env python
#
#  Angle Servo Control used from the github of Mjorvai
#  Link to the github is: https://github.com/Mjrovai/WebCam-Pan-Tilt-Control-via-Flask
#  Execute with parameter ==> sudo python3 servoCtrl.py <servo GPIO> <servo_angle> 
  
from time import sleep
import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)


def setServoAngle(servo, angle):
  # Modified values from the original code to fit the design of our servo and it's flexibility
	assert angle >=30 and angle <= 165
	pwm = GPIO.PWM(servo, 50)
	pwm.start(8)
	dutyCycle = angle / 18. + 3.
	pwm.ChangeDutyCycle(dutyCycle)
	sleep(0.3)
	pwm.stop()

if __name__ == '__main__':
	import sys
	servo = int(sys.argv[1])
	GPIO.setup(servo, GPIO.OUT)
	setServoAngle(servo, int(sys.argv[2]))
	GPIO.cleanup()
